#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

COMMIT_MSG_FILE=$1
BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

get_number_between_slashes() {
  local regex="\/([0-9]+)\/.*"
  if [[ $BRANCH_NAME =~ $regex ]]; then
    echo "${BASH_REMATCH[1]}"
  fi
}

NUMBER_BETWEEN_SLASHES=$(get_number_between_slashes)

if [ -n "$NUMBER_BETWEEN_SLASHES" ]; then
  sed -i.bak "1s/^/$NUMBER_BETWEEN_SLASHES: /" "$COMMIT_MSG_FILE"
fi
